import { QueryProvider } from "@/components/providers/query-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SyncProvider from "@/providers/SyncProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head> */}
      {/*   <script */}
      {/*     crossOrigin="anonymous" */}
      {/*     src="//unpkg.com/react-scan/dist/auto.global.js" */}
      {/*   /> */}
      {/* </head> */}
      <body
        className={cn(
          "min-h-screen bg-[#151218] text-slate-100 antialiased",
          inter.className,
        )}
      >
        <div className="relative min-h-screen overflow-hidden">
          <div className="background-gradient" aria-hidden="true" />
          <SyncProvider>
            <QueryProvider>{children}</QueryProvider>
          </SyncProvider>
        </div>
      </body>
    </html>
  );
}
