import { QueryProvider } from "@/components/providers/query-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head> */}
      {/*   <script */}
      {/*     crossOrigin="anonymous" */}
      {/*     src="//unpkg.com/react-scan/dist/auto.global.js" */}
      {/*   /> */}
      {/* </head> */}
      <body
        className={cn(
          "min-h-screen bg-[#151218] text-slate-100 antialiased",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <div className="relative min-h-screen overflow-hidden">
          {/* background glow blobs */}
          <div className="pointer-events-none absolute inset-0 -z-10">
            <div className="absolute -top-32 -left-16 h-80 w-80 rounded-full bg-emerald-500/20 blur-3xl" />
            <div className="absolute bottom-0 right-0 h-96 w-96 rounded-full bg-sky-500/15 blur-3xl" />
          </div>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
